version: 0.2

#  <groupId>com.revature</groupId>
#  <artifactId>ToDoTwo</artifactId>
#  <version>0.1</version>
#  <packaging>war</packaging>

phases:
  install:
    runtime-versions:
      java: corretto8

  build:
    commands:
      - echo ================== START BUILD ==================
      - mvn package -DskipTests
  post_build:
    commands:
      - echo ================== POST BUILD ==================
      - ls -al
      - mv target/devops-demo-0.1.war devops-demo-0.1.war
artifacts:
  files:
    - devops-demo-0.1.war